apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: "http://zipkin.default.svc.cluster.local:9411/api/v2/spans"

# apiVersion: dapr.io/v1alpha1
# kind: Configuration
# metadata:
#   name: appconfig
# spec:
#   tracing:
#     samplingRate: "1"
#     stdout: true
#     otel:
#       endpointAddress: "localhost:4317"
#       isSecure: false
#       protocol: grpc
#   metrics:
#     enabled: true
#   logging:
#     apiLogging:
#       enabled: true
#       obfuscateURLs: true
#       omitHealthChecks: true
