version: '3'
services:
  ############################
  # Node app + Dapr sidecar
  ############################
  divide:
    build: ./node
    ports:
      - "4000"
    deploy:
      replicas: 2
    depends_on:
      - redis
      - placement
    networks:
      - dapr-distributed-network
  divide-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "divideapp",
     "-app-port", "4000",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - divide
    network_mode: "service:divide"
  ############################
  # Python app + Dapr sidecar
  ############################
  multiply:
    build: ./python
    ports:
      - "5001"
    deploy:
      replicas: 2
    depends_on:
      - redis
      - placement
    networks:
      - dapr-distributed-network
  multiply-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "multiplyapp",
     "-app-port", "5001",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - multiply
    network_mode: "service:multiply"
  ############################
  # Go app + Dapr sidecar
  ############################
  add:
    build: ./go
    ports:
      - "6000"
    deploy:
      replicas: 2
    depends_on:
      - redis
      - placement
    networks:
      - dapr-distributed-network
  add-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "addapp",
     "-app-port", "6000",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - add
    network_mode: "service:add"
  ############################
  # react app + Dapr sidecar
  ############################
  calculator:
    build: ./react-calculator
    ports:
      - "8000:8080"
      - "3500"
      - "50001"
    depends_on:
      - redis
      - placement
    networks:
      - dapr-distributed-network
  calculator-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "calculator-front-end",
     "-app-port", "8080",
     "-dapr-http-port", "3500",
     "-dapr-grpc-port", "50001",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - calculator
    network_mode: "service:calculator"
  ############################
  # dotnet app + Dapr sidecar
  ############################
  subtract:
    build: ./csharp
    ports:
      - "80"
    deploy:
      replicas: 2
    depends_on:
      - redis
      - placement
    networks:
      - dapr-distributed-network
  subtract-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "subtractapp",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-dapr-grpc-port", "50001",
     "-placement-host-address", "placement:50006",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - subtract
    network_mode: "service:subtract"
  ############################
  # Dapr placement service
  ############################
  placement:
    image: "daprio/dapr"
    command: ["./placement", "-port", "50006"]
    ports:
      - "50006:50006"
    networks:
      - dapr-distributed-network
  ############################
  # Redis state store
  ############################
  redis:
    image: docker.io/bitnami/redis:7.2
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - dapr-distributed-network
    volumes:
      - 'redis_data:/bitnami/redis/data'

volumes:
  redis_data:
    driver: local
networks:
    dapr-distributed-network:
